### ISSUE TITLE
alibuild clean: cannot handle multiple development packages

### ISSUE THREAD

**Issue by dstocco** [alisw/alibuild#325]
Dear all,
I used to have a development AliRoot/AliPhysics version linked to root v5:
ali-master:
  AliPhysics -> ../../refSrcs/AliPhysics/patches
  AliRoot -> ../../refSrcs/AliRoot/patches
  alidist(IB/v5-08/next)

I then decided to test root6. So I initialised a new alidist with IB/master/root6:

ali-root6:
  AliPhysics -> ../../refSrcs/AliPhysics/patches
  AliRoot -> ../../refSrcs/AliRoot/patches
  alidist(IB/master/root6)

My plan is to use both versions (ali-master and ali-root6), eventually slowly moving to root6.

However, when I did alibuild clean, it erased the root v5.
So I built ali-master again (it is fast since there is the TARS)...and this times it erased root v6.
In practice, it seems that the alibuild clean, cleans everything which is not associated to the "latest" build.
Can this be fixed so that, in case of several development versions, the clean only touches the packages that are used by nobody?

Thanks in advance,
best regards,
Diego

**Comment by ktf** [comment]
Strange. This should be working just fine.

Are you using `aliBuild 1.3.0`? Can you setup both branches and then tell me what:

```
echo "Links"
find  sw/osx_x86-64/ -name "latest*"
echo "Clean"
aliBuild clean --dry-run
```

tells you?

**Comment by dstocco** [comment]
Ciao Giulio,
I'm using aliBuild master from git (updated to yesterday).

In the meanwhile, I initialised a custom directory for ROOT6, with aliBuild init -z ali-root6 master
so that I can decide what version to use.
Anyways, I still have the problem with geant3, which is the only dependency left which changes between ali-root6 and ali-master.
Indeed, here comes your output:

Links

sw/osx_x86-64//AliEn-CAs/latest
sw/osx_x86-64//AliEn-Runtime/latest
sw/osx_x86-64//AliPhysics/latest
sw/osx_x86-64//AliPhysics/latest-ali-master
sw/osx_x86-64//AliPhysics/latest-ali-root6
sw/osx_x86-64//AliRoot/latest
sw/osx_x86-64//AliRoot/latest-ali-master
sw/osx_x86-64//AliRoot/latest-ali-muonhlt
sw/osx_x86-64//AliRoot/latest-ali-root6
sw/osx_x86-64//ApMon-CPP/latest
sw/osx_x86-64//boost/latest
sw/osx_x86-64//cgal/latest
sw/osx_x86-64//defaults-release/latest
sw/osx_x86-64//fastjet/latest
sw/osx_x86-64//GEANT3/latest
sw/osx_x86-64//GMP/latest
sw/osx_x86-64//GSL/latest
sw/osx_x86-64//gSOAP/latest
sw/osx_x86-64//lhapdf5/latest
sw/osx_x86-64//MonALISA-gSOAP-client/latest
sw/osx_x86-64//MPFR/latest
sw/osx_x86-64//nanomsg/latest
sw/osx_x86-64//POWHEG/latest
sw/osx_x86-64//POWHEG/latest-powheg
sw/osx_x86-64//protobuf/latest
sw/osx_x86-64//ROOT/latest
sw/osx_x86-64//ROOT/latest-ali-muonhlt
sw/osx_x86-64//ROOT/latest-ali-root6
sw/osx_x86-64//sodium/latest
sw/osx_x86-64//SWIG/latest
sw/osx_x86-64//UUID/latest
sw/osx_x86-64//xalienfs/latest
sw/osx_x86-64//XRootD/latest
sw/osx_x86-64//ZeroMQ/latest

Clean

This will delete the following directories
/Users/dstocco/Documents/projects/alice/software/sw/TMP
/Users/dstocco/Documents/projects/alice/software/sw/osx_x86-64/GEANT3/v2-1-4
/Users/dstocco/Documents/projects/alice/software/sw/osx_x86-64/GEANT3/v2-1-7
--dry-run / -n specified. Doing nothing.

Thanks,
ciao,
Diego

**Comment by ktf** [comment]
Indeed this is strange. You should have "latest-ali-root6" and 
"latest-ali-master" also for GEANT3. I will check.

**Comment by ktf** [comment]
Should be fixed by #361. Can you please try it out?

**Comment by dstocco** [comment]
Ciao Giulio,
I tried it out (with today's master of alibuild and IB/v5-08/next of alidist), but it seems I still have the issue.

I compile ali-master first (using v5-34-30-alice5) and O2 later (using v6-06-04-2).
If I do:
`ls -lrt $ALICE_WORK_DIR/osx_x86-64/ROOT/`
I have:
```
drwxr-xr-x  21 dstocco  staff  714 Aug 22 16:26 v6-06-04-2
drwxr-xr-x  23 dstocco  staff  782 Aug 22 17:04 v5-34-30-alice5-2
lrwxr-xr-x   1 dstocco  staff   10 Aug 22 21:29 latest -> v6-06-04-2
```

If I do:
`alibuild clean -n`
I get:
```
This will delete the following directories
/Users/dstocco/Documents/projects/alice/software/sw/TMP
/Users/dstocco/Documents/projects/alice/software/sw/osx_x86-64/GEANT3/v2-1-4
/Users/dstocco/Documents/projects/alice/software/sw/osx_x86-64/ROOT/v5-34-30-alice5-2
```

So, it still wants to delete the root which is not linked as "latest". Am I missing something?

Thanks,
cheers,
Diego

**Comment by ktf** [comment]
You need to rebuild once both version to fix an existing installation.

--
Ciao,
Giulio

**Comment by dstocco** [comment]
Ciao Giulio,
this is what I did.
After updating alibuild, I updated both O2 (linked to root6) and AliPhysics master (linked to root5), and build each of them with aliBuild.
What I wrote above was done after rebuilding.

Should I first manually clean something under ALICE_WORK_DIR and then build again?
Thanks,
ciao,
Diego

**Comment by ktf** [comment]
and you had the -z option, right?

**Comment by dstocco** [comment]
Yep:
`aliBuild -z -w $ALICE_WORK_DIR --disable GEANT4,GEANT4_VMC,fastjet build AliPhysics`

**Comment by ktf** [comment]
Ah, wait. You need to use next of aliBuild, not master.

**Comment by dstocco** [comment]
Ciao Giulio,
with next, it works!
From now on, should I use "next" instead of "master" if I want to test the new features?

Thanks,
ciao,
Diego

**Comment by ktf** [comment]
Well, next it a bit more bleeding edge.

**Comment by ktf** [comment]
While master is guaranteed to have been throughly tested (does not mean it cannot break, of course).

**Comment by ktf** [comment]
Anyways, please close this if you are happy.

**Comment by dstocco** [comment]
Sure,
closing it. Thanks a lot!
Diego
